# Generated by Django 3.0.2 on 2020-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, height_field=300, null=True, upload_to='', width_field=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
