# Generated by Django 3.0.2 on 2020-07-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20200706_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='product_id',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(to='products.OrderItems'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
