# Generated by Django 3.0.2 on 2020-07-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200706_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_date',
        ),
    ]
